NO MESSAGE SET

diff --git a/buildLinux b/buildLinux
--- a/buildLinux
+++ b/buildLinux
@@ -10,7 +10,10 @@ test -f /tmp/build/linux/vex++.x86_64 || {
   echo "fail exit"
   exit 1
 }
-7zz a -mx9 /tmp/build/linux.zip /tmp/build/linux/vex++.x86_64 /tmp/build/linux/vex++.pck /tmp/build/linux/ed25519.linux.template_debug.x86_64.so >/dev/null
+7zz a -mx9 /tmp/build/linux.zip /tmp/build/linux/vex++.x86_64 /tmp/build/linux/vex++.pck /tmp/build/linux/ed25519.linux.template_debug.x86_64.so >/dev/null || {
+  echo "fail exit"
+  exit 1
+}
 
 echo /tmp/build/linux.zip
 
diff --git a/buildWindows b/buildWindows
--- a/buildWindows
+++ b/buildWindows
@@ -10,7 +10,10 @@ test -f /tmp/build/windows/vex++.exe || {
   echo "fail exit"
   exit 1
 }
-7zz a -mx9 /tmp/build/windows.zip /tmp/build/windows/vex++.exe /tmp/build/windows/vex++.pck /tmp/build/windows/vex++.console.exe ed25519.windows.template_debug.x86_64.dll >/dev/null
+7zz a -mx9 /tmp/build/windows.zip /tmp/build/windows/vex++.exe /tmp/build/windows/vex++.pck /tmp/build/windows/vex++.console.exe /tmp/build/windows/ed25519.windows.template_debug.x86_64.dll >/dev/null || {
+  echo "fail exit"
+  exit 1
+}
 
 echo /tmp/build/windows.zip
 
